# Generated by Django 5.1.4 on 2024-12-16 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0002_amigo_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='amigo',
            name='familiar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amigos', to='familiares.familiar'),
        ),
    ]
